### ISSUE TITLE
关于训练结果

### ISSUE THREAD

**Issue by ziyuan-ss** [SJTUwbl/mfrl_pytorch#1]
请问，您复现的时候是否遇到过mfq的性能比ac还差的情况呢

**Comment by SJTUwbl** [comment]
还没有遇到过这种情况，训练结果与论文中基本一致。

**Comment by ziyuan-ss** [comment]
请问您mfq的超参数是如何设置的呢？我使用您的代码，用与原论文中一样的超参数，结果mfq的性能要比mfac差想和您请教一下超参数的设置问题。希望可以得到您的回复。谢谢

--------------原始邮件--------------
发件人："SJTUwbl ***@***.***&gt;;
发送时间：2021年11月21日(星期天) 中午12:46
收件人："SJTUwbl/mfrl_pytorch" ***@***.***&gt;;
抄送："周子渊 ***@***.***&gt;;"Author ***@***.***&gt;;
主题：Re: [SJTUwbl/mfrl_pytorch] 关于训练结果 (Issue #1)
-----------------------------------

 

 
还没有遇到过这种情况，训练结果与论文中基本一致。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by SJTUwbl** [comment]
代码与原文一致，不知道你的是在哪个环境中验证的，如果是battle的话，可以可视化对抗过程看一下是否代码正常运行。

**Comment by SJTUwbl** [comment]
代码与原文一致，不知道你的是在哪个环境中验证的，如果是battle的话，可以可视化对抗过程看一下是否代码正常运行。另外不知道是否用论文源代码验证过你的想法。

**Comment by ziyuan-ss** [comment]
我是在battle的环境中进行实验的，在论文源码上也进行过一次实验，结果mfq比mfac要差。之后就在您提供的代码上调参了。我觉得应该是我的哪些参数设置有问题，所以想和您请教一下。

--------------原始邮件--------------
发件人："SJTUwbl ***@***.***&gt;;
发送时间：2021年11月21日(星期天) 中午1:41
收件人："SJTUwbl/mfrl_pytorch" ***@***.***&gt;;
抄送："周子渊 ***@***.***&gt;;"Author ***@***.***&gt;;
主题：Re: [SJTUwbl/mfrl_pytorch] 关于训练结果 (Issue #1)
-----------------------------------

 

 
代码与原文一致，不知道你的是在哪个环境中验证的，如果是battle的话，可以可视化对抗过程看一下是否代码正常运行。另外不知道是否用论文源代码验证过你的想法。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by SJTUwbl** [comment]
可以可视化对抗过程看一下是否运行正常，或者调解下battle.py文件中`runner.run(1.0, k, win_cnt=win_cnt)`的eps参数。

**Comment by ziyuan-ss** [comment]
好的，多谢，我调试一下

--------------原始邮件--------------
发件人："SJTUwbl ***@***.***&gt;;
发送时间：2021年11月21日(星期天) 中午1:52
收件人："SJTUwbl/mfrl_pytorch" ***@***.***&gt;;
抄送："周子渊 ***@***.***&gt;;"Author ***@***.***&gt;;
主题：Re: [SJTUwbl/mfrl_pytorch] 关于训练结果 (Issue #1)
-----------------------------------

 

 
可以可视化对抗过程看一下是否运行正常，或者调解下battle.py文件中runner.run(1.0, k, win_cnt=win_cnt)的eps参数。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
